"""
Pre-defined ticket codes for the voting system.
These tickets are hardcoded and cannot be generated by admin.
"""

# Pre-defined ticket codes - only valid seat codes
PREDEFINED_TICKETS = [
    # D13 Section
    "D13.1",
    "D13.2",
    "D13.3",
    "D13.4",
    "D13.5",
    "D13.6",
    
    # A2.R3 Section
    "A2.R3.1",
    "A2.R3.2",
    "A2.R3.3",
    "A2.R3.4",
    "A2.R3.5",
    "A2.R3.6",
    "A2.R3.7",
    "A2.R3.8",
    
    # A1.R3 Section
    "A1.R3.2"
]

def get_predefined_tickets():
    """Get the list of pre-defined ticket codes"""
    return PREDEFINED_TICKETS.copy()

def is_valid_ticket_code(ticket_code):
    """Check if a ticket code is in the pre-defined list.
    The check is case-insensitive and ignores whitespace in the code.
    """
    return normalize_ticket_code(ticket_code) in PREDEFINED_TICKETS_NORMALIZED

def get_ticket_count():
    """Get the total number of pre-defined tickets"""
    return len(PREDEFINED_TICKETS)

# Normalization helpers (case-insensitive, ignore spaces)
PREDEFINED_TICKETS_NORMALIZED = {code.upper() for code in PREDEFINED_TICKETS}

def normalize_ticket_code(ticket_code: str) -> str:
    """Normalize a ticket code by removing spaces and uppercasing."""
    if not ticket_code:
        return ""
    return ticket_code.replace(" ", "").upper()
